version: '3.7'
services:
  #Django container
  app:
    build: .
    env_file:
      - core/settings/.env
    volumes:
    - $PWD/:/app
    - static:/app/static
    networks:
      - main
    depends_on:
      - db

  #Database Container
  db:
    image: postgres:10.1-alpine
    networks:
      - main
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  #Nginx container
  nginx:
    image: nginx
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/app/static
    ports:
    - "80:80"
    networks:
    - main  # Add the container to the network "main"
    depends_on:
    - app

networks:
  main:
volumes:
  postgres_data:
  static:



