version: '3.6'

services:
  app:
    container_name: ceb-simple-app
    build:
      context: ../..
      dockerfile: ./setup/simple/Dockerfile
    restart: "no"
    tty: true
    environment:
    #- APP_UID=$APP_UID
    #- APP_GID=$APP_GID
    - PYTHONDONTWRITEBYTECODE=1
    - PYTHONUNBUFFERED=1
    volumes:
    - ./docker-entrypoint.sh:/app/docker-entrypoint.sh:ro
    - ../../src/:/app/src/:rw
    - ../../requirements/:/app/requirements/:rw
    - ../../.flake8:/app/.flake8:ro
    - ../../.local/simple/config.env:/app/config.env:ro
    - ../../.local/simple/log/app/:/app/log/:rw
    - ../../.local/simple/db.sqlite3:/app/db.sqlite3:rw
    - ../../.local/simple/static/:/app/static:rw
    ports:
    - "8000:8000"
    networks:
    - main

networks:
  main:
    name: ceb-simple
